version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: demo01
    volumes:
      - ${DB_DATA:-./mongo-data}:/data/db
  redis:
    image: redis
    restart: always
  pubsub:
    build: ./
    ports:
      - 4040:4040
    environment:
      REDIS_HOST: redis
      MONGO_URL: mongodb://mongo
    depends_on:
      - mongodb
      - redis

